### ISSUE TITLE
encrypt more files

### ISSUE THREAD

**Issue by Ccode-lang** [CPScript/LOL-ransom#1]
We could use os.walk to get files to encrypt.

**Comment by CPScript** [comment]
ok

**Comment by CPScript** [comment]
BTW add me on discord Fe4RLess#0001

**Comment by CPScript** [comment]
also tell me your user becuase i got over 150 friend requests

**Comment by Ccode-lang** [comment]
I'm Ccode#3898 and I sent you a request.
