### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by b3lief** [CPScript/LOL-ransom#3]
This code was obtained from networkchuck.

**Comment by CPScript** [comment]
> This code was obtained from networkchuck.

i do watch him, and no it wasn't

**Comment by CPScript** [comment]
have a good day <3

**Comment by b3lief** [comment]
> > This code was obtained from networkchuck.
> 
> i do watch him, and no it wasn't

it is though LMFAO

**Comment by CPScript** [comment]
> This code was obtained from networkchuck.

Some of this code was gotten from the website---> https://www.geeksforgeeks.org
